server:
  port: 8000
#spring.main.allow-bean-definition-overriding=true
spring:
  application:
    name: thicket-gateway-server

  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 10000
      routes:
        # member service 라우팅 설정
        - id: member-service
          uri: lb://THICKET-MEMBER
          predicates:
            - Path=/thicket-member/**
          filters:
            - RewritePath=/thicket-member/(?<segment>.*), /$\{segment}

        # ticket service 라우팅 설정
        - id: ticket-service
          uri: lb://THICKET-TICKET
          predicates:
            - Path=/thicket-ticket/**
          filters:
            - RewritePath=/thicket-ticket/(?<segment>.*), /$\{segment}

        # show service 라우팅 설정
        - id: show-service
          uri: lb://THICKET-SHOW
          predicates:
            - Path=/thicket-show/**
          filters:
            - RewritePath=/thicket-show/(?<segment>.*), /$\{segment}

      default-filters:
        - name: GlobalFilter

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka