spring:
  profiles:
    active: localDB
  datasource:
    driver-class-name: ${localDB.driver}
    username: ${localDB.username_}
    password:
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  properties:
    secret: ${jwt.secret}
    access-token-expiration-seconds: 900 # 900 15분
    refresh-token-expiration-seconds: 1209600 # 1209600 14일
    token-prefix: Bearer
  response:
    access-token-header-name: Authorization
    refresh-token-header-name: Refresh-Token