spring:
  profiles:
    active: localDB,mail,redis

  datasource:
    driver-class-name: ${localDB.driver}
    username: ${localDB.username_}
    password:
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${mail.host} #HTTP 서버 호스트
    port: ${mail.port} # SMTP 서버 포트
    username: ${mail.username} # SMTP 서버 로그인 아이디 (발신자)
    password: ${mail.password} # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  #  web:
  #    cors:
  #      allow-credentials: true
  #      allowed-headers: "*"
  #      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  #      allowed-origins: "http://localhost:3000"
  #      max-age: 3600

  resources:
    add-mappings: false  # /error 경로에 대한 CORS 설정

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  properties:
    secret: ${jwt.secret}
    access-token-expiration-seconds: 900 # 900 15분
    refresh-token-expiration-seconds: 1209600 # 1209600 14일
    token-prefix: Bearer
  response:
    access-token-header-name: Authorization
    refresh-token-header-name: Refresh-Token